export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const VIDEO_REPOSITORY = 'VIDEO_REPOSITORY';
export const VIDEO_SUBTITLES_REPOSITORY = 'VIDEO_SUBTITLES_REPOSITORY';
export const VIDEO_INTERESTS_REPOSITORY = 'VIDEO_INTERESTS_REPOSITORY';
export const SUBTITLES_REPOSITORY = 'SUBTITLES_REPOSITORY';
export const SNIPPET_REPOSITORY = 'SNIPPET_REPOSITORY';
export const EDITORS_REPOSITORY = 'EDITORS_REPOSITORY';
export const INTERESTS_REPOSITORY = 'INTERESTS_REPOSITORY';

export const YOUTUBE_VIDEO_ID_LENGTH = 11;
export const PRIORITY_VIDEO_DEFAULT = 999999;
